name: 'Upload Image'
on:
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - env:
        GITHUB_CONTEXT: ${{ github.event.client_payload.data }}
      run: echo "TITLE=$(echo $GITHUB_CONTEXT | jq '.title' -r)" >> $GITHUB_ENV
    - env:
        GITHUB_CONTEXT: ${{ github.event.client_payload.data }}
      run: echo "CONTENTS=$(echo $GITHUB_CONTEXT | jq '.contents' -r)" >> $GITHUB_ENV
    - env:
        GITHUB_CONTEXT: ${{ github.event.client_payload.data }}
      run: echo "ID=$(echo $GITHUB_CONTEXT | jq '.id' -r)" >> $GITHUB_ENV
    - env:
        GITHUB_CONTEXT: ${{ github.event.client_payload.data }}
      run: echo "VISIBILITY=$(echo $GITHUB_CONTEXT | jq '.visibility' -r)" >> $GITHUB_ENV
    - env:
        GITHUB_CONTEXT: ${{ github.event.client_payload.data }}
      run: echo "MODE=$(echo $GITHUB_CONTEXT | jq '.mode' -r)" >> $GITHUB_ENV
    - name: Writing Snippet to File
      run: node addsnippet.sh
    - name: Committing changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: Github Actions
        author_email: actions@github.com
        pull_strategy: '--rebase'